# ========================================================
# UPDATED: 02_RandomForest_FigureOutNumPredictors.R
# ========================================================

source(file.path("code", "paths+packages.R"))
library(tidymodels)
library(ranger)
library(dplyr)
library(ggplot2)

####
#### prep data
####

# 1. Load Data
gage_sample <- 
  readr::read_csv(file = file.path("results/Mine", "Physiographic_data.csv"))

gage_regions <- 
  readr::read_csv(file.path("results/Mine", "station_ai_regions.csv"))

gage_sample_annual <-
  readr::read_csv(file = file.path("results/Mine", "gauges_annual_summary_out.csv"))

metrics <- c("Zero_Flow_Days_sum", "hydro_doy", "mean_dry_down_days")
regions <- c("National", na.omit(unique(gage_sample_annual$region)))

# 2. DEFINING PREDICTORS (Exact same as Script 01)
predictors_climate <- c(
  'tmax', 'tmin', 'tavg', 'srad_lw(w/m2)', 'srad_sw(w/m2)', 'wind_u(m/s)', 'wind_v(m/s)',
  'wind(m/s)', 'rel_hum(%)', 'sm_lvl1(kg/m2)', 'sm_lvl2(kg/m2)', 'sm_lvl3(kg/m2)', 'sm_lvl4(kg/m2)', 
  'p', 'pet', 'aet', 'evap_canopy(mm/day)', 'evap_surface(mm/day)', 'tmax_djf', 'tmax_jjas',
  'tmax_mam', 'tmax_on', 'tmin_djf', 'tmin_jjas', 'tmin_mam', 'tmin_on', 'tavg_djf', 'tavg_jjas', 
  'tavg_mam', 'tavg_on', 'p_djf', 'p_jjas', 'p_mam', 'p_on', 'pet_djf', 'pet_jjas', 'pet_mam', 
  'pet_on', 'aet_djf', 'aet_jjas', 'aet_mam', 'aet_on', 'evap_canopy(mm/day)_djf',
  'evap_canopy(mm/day)_jjas', 'evap_canopy(mm/day)_mam', 'evap_canopy(mm/day)_on', 
  'evap_surface(mm/day)_djf', 'evap_surface(mm/day)_jjas', 'evap_surface(mm/day)_mam',
  'evap_surface(mm/day)_on', 'spei3_drought_count', 'spei6_drought_count',
  'spei12_drought_count', 'spei24_drought_count', 'spei3_drought_valid_n',
  'spei6_drought_valid_n', 'spei12_drought_valid_n', 'spei24_drought_valid_n', 
  'spei3_drought_max_spell', 'spei6_drought_max_spell', 'spei12_drought_max_spell',
  'spei24_drought_max_spell', 'spei3_drought_count_frac', 'spei6_drought_count_frac', 
  'spei12_drought_count_frac', 'spei24_drought_count_frac'
)

predictors_human <- c('urban_pct', 'Total_Dams_So_Far', 'Total_Volume_So_Far')

predictors_static <- c(
  'num_dams', 'res_store_sum', 'total_storage', 'geol_porosity', 'geol_permeability', 
  'carb_rocks_frac', 'lai_mean', 'lai_min', 'lai_max', 'lai_diff', 'soil_depth', 
  'soil_conductivity_top', 'soil_conductivity_sub', 'soil_awc_top', 'soil_awc_sub', 
  'soil_awsc_min', 'soil_awsc_max', 'soil_awsc_major', 'sand_frac_top', 'sand_frac_sub', 
  'silt_frac_top', 'silt_frac_sub', 'clay_frac_top', 'clay_frac_sub', 'gravel_frac_top', 
  'gravel_frac_sub', 'bulkdens_top_major', 'bulkdense_top_mean', 'bulkdens_sub_mean', 
  'org_carb_top_major', 'org_carb_top_mean', 'org_carb_sub_major', 'org_carb_sub_mean', 
  'organic_frac_top', 'organic_frac_sub', 'cwc_lat', 'cwc_lon', 'elev_mean', 'elev_median', 
  'elev_min', 'elev_max', 'slope_mean', 'slope_median', 'slope_min', 'slope_max', 
  'cwc_area', 'dpsbar', 'sinuosity' 
)

# 3. Sanitize names so formulas don't crash
names(gage_sample_annual) <- make.names(names(gage_sample_annual))
names(gage_sample) <- make.names(names(gage_sample))
predictors_climate <- make.names(predictors_climate)
predictors_human <- make.names(predictors_human)
predictors_static <- make.names(predictors_static)
metrics <- make.names(metrics)

## 4. Calculate previous year climate metrics
gage_sample_prevyear <- 
  gage_sample_annual %>% 
  dplyr::select(gauge_id, hydro_year, all_of(predictors_climate)) %>% 
  dplyr::mutate(wyearjoin = hydro_year + 1) %>% 
  dplyr::select(-hydro_year)

names(gage_sample_prevyear)[names(gage_sample_prevyear) %in% predictors_climate] <- 
  paste0(names(gage_sample_prevyear)[names(gage_sample_prevyear) %in% predictors_climate], ".previous")

## 5. Combine into one master fit dataset
fit_data_in <- 
  gage_sample_annual %>% 
  dplyr::select(gauge_id, hydro_year, Sample, region, all_of(metrics), 
                all_of(predictors_climate), any_of(predictors_human)) %>% 
  dplyr::left_join(gage_sample_prevyear, by = c("gauge_id", "hydro_year"="wyearjoin")) %>% 
  dplyr::left_join(gage_sample %>% dplyr::select(gauge_id, any_of(predictors_static)), by = "gauge_id")

## ========================================================
## Test number of predictors to use in final models
## ========================================================

# Testing model accuracy from 10 variables up to 50 variables (in increments of 2 to save time)
pred_test_range <- seq(10, 50, by = 2)  

# set up model engine
rf_engine <- 
  rand_forest() %>% 
  set_engine("ranger", num.threads = (parallel::detectCores() - 1)) %>% 
  set_mode("regression")

fit_predtest <- data.frame()

# for (m in metrics){
#   # Read the Importance ranking generated by Script 01
#   rf_var_importance <- 
#     file.path("results/Mine", paste0("01_RandomForest_PreliminaryVariableImportance_", m, "_National.csv")) %>% 
#     readr::read_csv(show_col_types = FALSE)
#   
#   for (n_pred in pred_test_range){
#     
#     # get top 'n' predictor variables
#     rf_var_predtest <- rf_var_importance %>% dplyr::top_n(n = n_pred, wt = ImpCondPerm)
#     
#     # subset
#     fit_data_predtest <- 
#       fit_data_in %>% 
#       subset(Sample == "Train") %>% 
#       dplyr::select(all_of(m), all_of(rf_var_predtest$predictor)) %>%  
#       subset(complete.cases(.))
#     
#     names(fit_data_predtest)[names(fit_data_predtest) == m] <- "observed"
#     
#     # fit model
#     set.seed(1)
#     
#     rf_recipe <- recipe(observed ~ ., data = fit_data_predtest) %>%
#       step_normalize(all_predictors(), -all_outcomes())
#     
#     rf_wflow <- workflow() %>% 
#       add_model(rf_engine) %>% 
#       add_recipe(rf_recipe)
#     
#     rf_fit <- rf_wflow %>% parsnip::fit(data = fit_data_predtest)
#     
#     # Append results
#     current_result <- tibble::tibble(
#       metric = m,
#       n = n_pred,
#       OOBmse = extract_fit_engine(rf_fit)$prediction.error,
#       OOBr2 = extract_fit_engine(rf_fit)$r.squared
#     )
#     
#     fit_predtest <- dplyr::bind_rows(fit_predtest, current_result)
#     
#     print(paste0(m, " - ", n_pred, " predictors complete"))
#   }
# }


##################### LOOP through every region as well #####################

## ========================================================
## Test number of predictors to use in final models (NOW FOR ALL REGIONS)
## ========================================================

for (m in metrics){
  for (r in regions){
    
    # Safely format the region name to match the CSVs
    r_safe <- gsub(" ", "", r, fixed = TRUE)
    
    # Load the specific importance file for this Metric AND Region
    imp_file <- file.path("results/Mine", paste0("01_RandomForest_PreliminaryVariableImportance_", m, "_", r_safe, ".csv"))
    
    # Skip if the file doesn't exist (e.g., if a region was dropped for having < 20 stations)
    if(!file.exists(imp_file)) next
    
    rf_var_importance <- readr::read_csv(imp_file, show_col_types = FALSE)
    
    # Filter the actual dataset to the specific region
    if (r == "National") {
      fit_data_r <- fit_data_in
    } else {
      fit_data_r <- subset(fit_data_in, region == r)
    }
    
    for (n_pred in pred_test_range){
      
      rf_var_predtest <- rf_var_importance %>% dplyr::top_n(n = n_pred, wt = ImpCondPerm)
      
      fit_data_predtest <- fit_data_r %>% 
        subset(Sample == "Train") %>% 
        dplyr::select(all_of(m), all_of(rf_var_predtest$predictor)) %>%  
        subset(complete.cases(.))
      
      names(fit_data_predtest)[names(fit_data_predtest) == m] <- "observed"
      
      set.seed(1)
      rf_recipe <- recipe(observed ~ ., data = fit_data_predtest) %>%
        step_normalize(all_predictors(), -all_outcomes())
      
      rf_wflow <- workflow() %>% add_model(rf_engine) %>% add_recipe(rf_recipe)
      rf_fit <- rf_wflow %>% parsnip::fit(data = fit_data_predtest)
      
      current_result <- tibble::tibble(
        metric = m,
        region = r,          # <--- Now tracking the region!
        n = n_pred,
        OOBmse = extract_fit_engine(rf_fit)$prediction.error,
        OOBr2 = extract_fit_engine(rf_fit)$r.squared
      )
      
      fit_predtest <- dplyr::bind_rows(fit_predtest, current_result)
    }
    print(paste0(m, " - ", r, " predictors complete"))
  }
}

# Save the massive new CSV containing all regions
fit_predtest %>% readr::write_csv(file = file.path("results/Mine2", "02_RandomForest_FigureOutNumPredictors.csv"))

# Calculate the optimal number of predictors for EACH metric AND region!
npred_final <- fit_predtest %>% 
  dplyr::group_by(metric, region) %>% 
  dplyr::filter(OOBmse == min(OOBmse)) %>%
  dplyr::select(metric, region, npred = n) %>%
  dplyr::distinct()

print(npred_final)


# ========================================================
# Plot and save separate MSE and R2 graphs for every region
# ========================================================
if(!dir.exists("figures_manuscript")) dir.create("figures_manuscript")

for(r in regions) {
  r_data <- subset(fit_predtest, region == r)
  r_opt <- subset(npred_final, region == r)
  
  if(nrow(r_data) == 0) next
  
  # 1. Generate and save MSE Plot
  p_mse <- ggplot(r_data, aes(x = n, y = OOBmse)) + 
    geom_vline(data = r_opt, aes(xintercept = npred), color = "red", linetype = "dashed") +
    geom_point() + geom_line() +
    facet_grid(metric~., scales = "free_y",
               labeller = as_labeller(c("Zero_Flow_Days_sum" = "Annual No-Flow\nDays", 
                                        "mean_dry_down_days" = "Days from Peak\nto No Flow",
                                        "hydro_doy" = "First No-Flow Day\n[climate year]"))) +
    labs(title = paste("Random Forest MSE -", r), 
         subtitle = "Red dashed line indicates mathematical minimum MSE",
         x = "Number of Predictors", 
         y = "OOB MSE [Training gages only]") +
    theme_bw()
  
  ggsave(file.path("figures_manuscript/Mine2", paste0("RandomForest_MSEvNumberPredictors_", gsub(" ", "", r), ".png")),
         plot = p_mse, width = 150, height = 150, units = "mm")
  
  # 2. Generate and save R-Squared (R2) Plot
  p_r2 <- ggplot(r_data, aes(x = n, y = OOBr2)) + 
    geom_vline(data = r_opt, aes(xintercept = npred), color = "red", linetype = "dashed") +
    geom_point() + geom_line() +
    facet_grid(metric~., scales = "free_y",
               labeller = as_labeller(c("Zero_Flow_Days_sum" = "Annual No-Flow\nDays", 
                                        "mean_dry_down_days" = "Days from Peak\nto No Flow",
                                        "hydro_doy" = "First No-Flow Day\n[climate year]"))) +
    labs(title = paste("Random Forest R2 -", r), 
         subtitle = "Red dashed line indicates the chosen model (minimum MSE)",
         x = "Number of Predictors", 
         y = expression("OOB R"^2 * " [Training gages only]")) +
    theme_bw()
  
  ggsave(file.path("figures_manuscript/Mine2", paste0("RandomForest_R2vNumberPredictors_", gsub(" ", "", r), ".png")),
         plot = p_r2, width = 150, height = 150, units = "mm")
}

print("MSE and R2 plotting complete for all regions! Check the figures_manuscript folder.")